# Generated by Django 5.1.7 on 2025-03-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_keywords_alter_article_target_audience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='content_url',
            field=models.URLField(default=''),
        ),
    ]
