# Generated by Django 5.1.7 on 2025-03-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_content_article_content_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_url_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
