# Generated by Django 5.1.7 on 2025-03-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_content_url_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_url',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
